"""add request_stats table

Revision ID: af9c1ed9fb60
Revises: 001_initial
Create Date: 2026-01-05 21:39:14.832429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af9c1ed9fb60'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи'),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='Telegram user ID'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='Telegram username (без @)'),
    sa.Column('request_time', sa.DateTime(), nullable=False, comment='Время запроса'),
    sa.Column('product_url', sa.Text(), nullable=True, comment='URL товара'),
    sa.Column('platform', sa.String(length=50), nullable=True, comment='Платформа (taobao/tmall/pinduoduo/1688/szwego)'),
    sa.Column('text_length', sa.Integer(), nullable=True, comment='Длина текста сообщения в символах'),
    sa.Column('images_count', sa.Integer(), nullable=False, comment='Количество изображений'),
    sa.Column('chunks_count', sa.Integer(), nullable=True, comment='Количество частей текста'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='Время обработки в миллисекундах'),
    sa.Column('request_id', sa.String(length=255), nullable=True, comment='Уникальный ID запроса (UUID)'),
    sa.Column('user_daily_limit', sa.Integer(), nullable=True, comment='Дневной лимит пользователя'),
    sa.Column('user_daily_count', sa.Integer(), nullable=True, comment='Использовано запросов за день'),
    sa.Column('user_daily_remaining', sa.Integer(), nullable=True, comment='Осталось запросов на день'),
    sa.Column('user_monthly_limit', sa.Integer(), nullable=True, comment='Месячный лимит пользователя'),
    sa.Column('user_monthly_count', sa.Integer(), nullable=True, comment='Использовано запросов за месяц'),
    sa.Column('user_monthly_remaining', sa.Integer(), nullable=True, comment='Осталось запросов на месяц'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True, comment='Количество входных токенов'),
    sa.Column('completion_tokens', sa.Integer(), nullable=True, comment='Количество выходных токенов'),
    sa.Column('total_tokens', sa.Integer(), nullable=True, comment='Общее количество токенов'),
    sa.Column('prompt_cost', sa.Float(), nullable=True, comment='Стоимость входных токенов (USD)'),
    sa.Column('completion_cost', sa.Float(), nullable=True, comment='Стоимость выходных токенов (USD)'),
    sa.Column('total_cost', sa.Float(), nullable=True, comment='Общая стоимость токенов (USD)'),
    sa.Column('global_daily_cost', sa.Float(), nullable=True, comment='Общая стоимость запросов за день (USD)'),
    sa.Column('global_monthly_cost', sa.Float(), nullable=True, comment='Общая стоимость запросов за месяц (USD)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Время создания записи'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_users_username'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_table('request_stats')
    # ### end Alembic commands ###
