name: Security - Vulnerability Scan

on:
  push:
    branches: [ main, develop ]
  schedule:
    # Каждый понедельник в 09:00 UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  dependency-scan:
    name: Scan Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit pip-audit
    
    - name: Run Safety check
      run: |
        safety check --json || true
      continue-on-error: true
    
    - name: Run pip-audit
      run: |
        pip-audit --requirement requirements.txt || true
      continue-on-error: true
    
    - name: Run Bandit security linter
      run: |
        bandit -r . -f json -o bandit-report.json || true
      continue-on-error: true
    
    - name: Upload Bandit report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-security-report
        path: bandit-report.json

  docker-scan:
    name: Scan Docker Image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build Docker image for scanning
      run: docker build -t taobao-scraper:scan .
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'taobao-scraper:scan'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy results to GitHub Security
      uses: github/codeql-action/upload-sarif@v4
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

